name: Get Patch Apps Info

on:
  push:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      # - name: Configure git
      #   run: |
      #      git config --global user.name "actions-user"
      #      git config --global user.email "actions@github.com"

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.11"

      - name: Install dependencies
        ## Ref: https://github.com/astral-sh/uv/issues/1386
        run: |
          pip install uv
          uv venv .venv
          echo "VIRTUAL_ENV=.venv" >> $GITHUB_ENV
          echo "$PWD/.venv/bin" >> $GITHUB_PATH
          uv pip install -r auto/scripts/requirements.txt

      #- name: Setup Chrome
      # uses: browser-actions/setup-chrome@v1.2.0

      - name: Update .py file contents
        env:
          sed_script: auto/scripts/rename.sh
        run: |
          sed -i 's@github_repo=.*@github_repo="${{ github.repository }}"@' "$sed_script"
          chmod +x "$sed_script"
          "$sed_script"

      - name: Commit Updated .py file contents
        uses: stefanzweifel/git-auto-commit-action@master
        with:
          skip_checkout: true
          file_pattern: .
          commit_message: 📝 Updated files

      - name: Run Python script
        run: |
          python auto/scripts/apps.py
          python auto/scripts/get-options.py
          python auto/scripts/parse-env-json.py

      - name: Commit Update file
        uses: stefanzweifel/git-auto-commit-action@master
        with:
          branch: changelogs
          create_branch: true
          skip_checkout: true
          file_pattern: "auto/json/env.json auto/apps/apps-merged.json"
          commit_options: "--allow-empty"
          commit_message: 📖 Parsed .env into env.json
          push_options: "--force"

      - name: Parse env.json to .env
        run: |
          python auto/scripts/parse-json-env.py

      - name: Commit Update file
        uses: stefanzweifel/git-auto-commit-action@master
        with:
          branch: changelogs
          create_branch: true
          skip_checkout: true
          file_pattern: .
          repository: .
          commit_options: "--allow-empty"
          commit_message: 📝 Add generated files
          push_options: "--force"
